### ISSUE TITLE
query edge source_id and target_id should match node ids

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/KnowledgeProviderScaffold#4]
https://github.com/NCATSTranslator/KnowledgeProviderScaffold/blob/eddb4e60cf0a75d3d5d2d3bcf8fe273eeb31784d/TranslatorQuery.json#L5

Note: [validation against the schema](http://transltr.io:7071/apidocs/#/default/post_validate_querygraph) for the query graph will not enforce this. This sort of semantic requirement cannot be encoded by JSON Schema/OpenAPI.

**Comment by MarkDWilliams** [comment]
Fixed by https://github.com/NCATSTranslator/KnowledgeProviderScaffold/commit/09b33fb7275d078f7909343effe244d6b77cadc6
